fix some glitches
qwq233/Nullgram pull request #101
Opened 2023-03-23 16:06 UTC by Henvy-Mango

# Tittle Here

fix some glitches
## Description

fix: touch views in IO thread
## Issues Fixed or Closed by This PR

## Check List

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] My code follows the code style of this project
- [ ] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2023-03-23 23:40 UTC, qwq233 requested changes

2023-03-23 23:40 UTC, qwq233 commented on TMessagesProj/src/main/java/top/qwq2333/nullgram/helpers/TranslateHelper.kt
> -import top.qwq2333.nullgram.translate.providers.BaiduTranslator
import打架了 不要星号import 不然每次自动reformat都会打架多changes

2023-03-24 01:19 UTC, Henvy-Mango commented
可以了，kotlin忘记取消配置import *

2023-03-24 01:46 UTC, qwq233 approved these changes

2023-03-24 01:46 UTC, merged