feat: improved translation
qwq233/Nullgram pull request #112
Opened 2023-04-07 07:07 UTC by Henvy-Mango

# Tittle Here

improved translation
## Description

add deepL translator
add yandex translator
## Issues Fixed or Closed by This PR

## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] My code follows the code style of this project
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2023-04-07 07:58 UTC, qwq233 requested changes

2023-04-07 07:58 UTC, qwq233 commented on TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/BaseTranslator.kt
> +            responseCharsetFallback = Charsets.UTF_8
fallback为什么要改

2023-04-07 07:58 UTC, qwq233 commented on TMessagesProj/src/main/java/top/qwq2333/nullgram/helpers/TranslateHelper.kt
> +        DeepLTranslator(5),
不要改变已有的num

2023-04-07 07:58 UTC, qwq233 commented on TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/GeneralSettingActivity.java
> +                        listAdapter.notifyItemRemoved(deepLFormalityRow);
这堆判断放update row方法 判断一次就够了 不需要额外remove那些

2023-04-07 07:58 UTC, qwq233 commented on TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/DeepLTranslator.kt
> +    const val FORMALITY_DEFAULT = 0
这里应用data class 和 序列化 可以参考 nicegram controller

2023-04-10 04:16 UTC, qwq233 submitted a review, later dismissed

2023-04-10 04:16 UTC, qwq233 commented
The base branch requires all commits to be signed.

2023-04-10 05:02 UTC, Henvy-Mango commented
> The base branch requires all commits to be signed.

好了

2023-04-10 07:51 UTC, qwq233 approved these changes

2023-04-10 07:52 UTC, merged