Do not compress videos
qwq233/Nullgram pull request #221
Opened 2024-03-13 01:32 UTC by megapro17

# Tittle Here
Send videos without modifying a file

## Description
When you're sending an video from android, it's not possible to send it without modifying video file. It will be remuxed (taking video stream into a new container, losing all it's metadata in the best case), even if you select the highest quality, if it has big enough bitrate, it will be forcefully compressed. It can't be disabled. Also it does compress audio horribly, with artifacts at the beginning.
These both action are very slow, it's much faster to send a video as document, which results that video is send exactly as is, without any changes (the same file hash). But it results to video is not embedded in chat, it does show as a document, not as video. Telegram Desktop and Telegram Web does not modify video file in any way, but video does show as a video.
My patch resolves this problem. Now you can send a video as document, but it will show as video anyway. Click file - gallery and select a video. The same behavior as is in official Telegram X client.
It also fixes the problem with missing video file name.

## Issues Fixed or Closed by This PR

## Check List

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] My code follows the code style of this project
- [ ] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2024-03-13 09:48 UTC, qwq233 requested changes
1. please sign your commit with a valid GnuPG signature
2. add `feat: ` prefix to your commit message

2024-03-13 14:48 UTC, qwq233 commented
uhh 
please read https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2024-03-15 06:06 UTC, megapro17 commented
> btw have you tested your changes?

Yes, it's merged in forkgram, and work fine

2024-03-20 17:17 UTC, megapro17 commented
how to confirm the requested changes?

2024-03-21 02:40 UTC, qwq233 commented
@megapro17 no time to review
sry
later this week/month i can do this

2024-03-24 08:22 UTC, qwq233 approved these changes

2024-03-24 08:22 UTC, merged